export const ROLE_OPTIONS = [
	{ value: "FEATURED", label: "Featured" },
	{ value: "PRODUCER", label: "Producer" },
	{ value: "SONGWRITER", label: "Songwriter" },
	{ value: "COMPOSER", label: "Composer" },
	{ value: "MIXER", label: "Mixer" },
	{ value: "ENGINEER", label: "Engineer" },
];

export const GENRE_OPTIONS = [
	"Pop",
	"Rock",
	"Hip-Hop",
	"R&B",
	"Electronic",
	"Jazz",
	"Classical",
	"Country",
	"Folk",
	"Latin",
	"Metal",
	"Punk",
	"Indie",
	"Alternative",
	"Blues",
	"Soul",
	"Reggae",
	"Funk",
	"Disco",
	"House",
	"Techno",
	"Ambient",
	"Other",
];
